# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_auto_20160604_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='registrado',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
