# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-04 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0003_auto_20160604_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrado',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
